---

- name: check php version
  fail:
    msg: "php_version|default('5') `{{ php_version|default('5') }}` not in ['5', '7.0', '7.1']"
  when: php_version is defined and php_version not in ['5', '7.0', '7.1']

- name: add key
  apt_key:
    url: 'https://www.dotdeb.org/dotdeb.gpg'
    state: present
  when: php_version is defined and php_version[0] == '7'

- name: Add repo
  apt_repository:
    repo: 'deb http://packages.dotdeb.org jessie all'
    state: present
  when: php_version is defined and php_version[0] == '7'

- name: Install php 7
  apt:
    update_cache: yes
    name: 'php7'
  when: php_version is defined and php_version[0] == '7'

- name: Install php{{ php_version }} libraries
  apt:
    name: "{{ item }}"
  with_items: ["php{{ php_version }}-curl", "php{{ php_version }}-gd", "php{{ php_version }}-mysql", "php{{ php_version }}-pgsql", "php{{ php_version }}-mcrypt", "php{{ php_version }}-imagick", "php{{ php_version }}-mbstring"]
  when: php_version is defined and php_version[0] == '7'

- name: Install php5
  apt:
    name: 'php5'
    update_cache: yes
  when: php_version is not defined or php_version == '5'

- name: Install php 5 libraries
  apt:
    name: "{{ item }}"
  with_items: [php5-curl, php5-gd, php5-mysql, php5-pgsql, php5-mcrypt, php5-imagick]
  when: php_version is not defined or php_version == '5'
